//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1.pod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractBMC
    {
        public int IdMEdicalCenter { get; set; }
        public int IdBranch { get; set; }
        public System.DateTime ContractPeriod { get; set; }
        public decimal ContractAmunt { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual MedicalCenter MedicalCenter { get; set; }
    }
}
