//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1.pod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IdContract { get; set; }
        public int IdClient { get; set; }
        public decimal AmountInsurance { get; set; }
        public int IdBranch { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime PeriodOfInsurance { get; set; }
        public int IdPayment { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
