//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika1.pod
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCenter
    {
        public int IdMedicalCenter { get; set; }
        public int IdCity { get; set; }
        public string Adress { get; set; }
        public string NumberOfPhone { get; set; }
    
        public virtual City City { get; set; }
        public virtual ContractBMC ContractBMC { get; set; }
    }
}
